name: Test and Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true # ensures Jest runs in CI mode, preventing accidental hangs

      - name: Build the project
        run: npm run build # use the appropriate build command for your project

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to Heroku
        if: success() # only deploy if tests pass
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        run: |
          heroku auth:token
          heroku git:remote -a $HEROKU_APP_NAME
          git push heroku main
